// <auto-generated-ish>
// Compatibility overloads used during modular/partial refactors.
// These are intentionally small and should be removed once all call-sites use canonical Guid-based APIs.
#nullable enable
using System;
using Safe0ne.Shared.Contracts;

namespace Safe0ne.DashboardServer.ControlPlane;

public partial class JsonFileControlPlane
{
    /// <summary>
    /// LEGACY_COMPAT: Some endpoints/call-sites still pass deviceId as a string.
    /// Prefer the Guid-based overload once migration completes.
    /// </summary>
    public bool TryRevokeDeviceToken(string deviceId, string revokedBy, string? reason, out ChildId? childId)
    {
        childId = null;

        if (!Guid.TryParse(deviceId, out var guid))
        {
            return false;
        }

        // Delegate to canonical Guid overload (should already exist).
        return TryRevokeDeviceToken(guid, revokedBy, reason, out childId);
    }
}
