// <auto-generated-ish>
// Compatibility overloads used during modular/partial refactors.
// These are intentionally small and should be removed once all call-sites use canonical Guid-based APIs.
//
// LEGACY-COMPAT: Temporary compatibility shim. | RemoveAfter: Wave1-Stability | Tracking: Docs/00_Shared/Legacy-Code-Registry.md
// TODO(LEGACY-REMOVE): Remove once all call-sites use the canonical Guid-based overload.
#nullable enable
using System;
using Safe0ne.Shared.Contracts;

namespace Safe0ne.DashboardServer.ControlPlane;

public partial class JsonFileControlPlane
{
    /// <summary>
    /// Some endpoints/call-sites still pass deviceId as a string. Prefer the Guid-based overload.
    /// </summary>
    public bool TryRevokeDeviceToken(string deviceId, string revokedBy, string? reason, out ChildId? childId)
    {
        childId = null;

        if (!Guid.TryParse(deviceId, out var guid))
        {
            return false;
        }

        // Delegate to canonical Guid overload.
        return TryRevokeDeviceToken(guid, revokedBy, reason, out childId);
    }
}
