// <auto-generated>
// LEGACY_COMPAT: This file previously contained a string-based TryRevokeDeviceToken overload.
// During the ControlPlane partial refactor we consolidated all endpoint/route-facing overloads into:
//   JsonFileControlPlane.EndpointCompat.StringOverloads.cs
//
// This file is intentionally kept (empty of duplicate members) to avoid patch-order collisions and to
// provide a clear future deletion point once all compat shims are retired.
//
// TODO(techdebt): delete JsonFileControlPlane.RevokeCompat.cs after canonical migration is complete
// and all callers use Guid/DeviceId typed overloads directly.
// </auto-generated>

namespace Safe0ne.DashboardServer.ControlPlane;

public sealed partial class JsonFileControlPlane
{
    // Intentionally empty.
}
