// <auto-generated by patch>
// NOTE: This file previously introduced a duplicate string overload for TryRevokeDeviceToken.
// We intentionally keep this file as a placeholder so patch application doesn't leave stale code behind,
// but we do NOT define any members here.
namespace Safe0ne.DashboardServer.ControlPlane;

public partial class JsonFileControlPlane
{
    // Intentionally empty. Revoke compatibility overloads live in:
    // JsonFileControlPlane.EndpointCompat.StringOverloads.cs
}
